# 넘파이(numpy)

In [ ]:
# 필요한 라이브러리 임포트
import numpy as np

## 넘파이 배열과 파이썬 리스트 비교

In [ ]:
# 파이썬 리스트 자료 구조 데이터 생성
list_data = [1,2,3]
print(f'파이썬 리스트: {list_data}')

print('-'*80)

# 넘파이 배열 생성
array_data = np.array(list_data)
print(f'넘파이 배열: {array_data}')

파이썬 리스트: [1, 2, 3]
--------------------------------------------------------------------------------
넘파이 배열: [1 2 3]

In [ ]:
# 파이썬 리스트와 넘파이 배열 차이점 확인

## 곱셈 연산

### 파이썬 리스트
result1 = list_data + list_data
print(f'파이썬 리스트에 대한 덧셈 연산의 결과: \n{result1}')

print('-'*80)

### sjavkdl qoduf
result2 = array_data + array_data
print(f'넘파이 배열에 대한 덧셈 연산의 결과: \n{result2}')

## 곱셈 연산
### 파이썬 리스트
result3 = []
for num in list_data:
    result3.append(num * 3)

print(f'파이썬 리스트에 대한 곱셈 연산의 결과: \n{result3}')

print('-'*80)

### 넘파이 배열
result4 = array_data * 3
print(f'넘파이 배열에 대한 곱셈 연산의 결과: \n{result4}')

print('-'*80)

## 통계 처리(평균 값 구하기)

### 파이썬 리스트
list_average = sum(list_data) / len(list_data)
print(f'파이썬 리스트에 대한 평균 값: {list_average}')

print('-'*80)

### 넘파이 배열
array_average = array_data.mean()
print(f'넘파이 배열에 대한 평균 값: {array_average}')

파이썬 리스트에 대한 덧셈 연산의 결과:
[1, 2, 3, 1, 2, 3]
--------------------------------------------------------------------------------
넘파이 배열에 대한 덧셈 연산의 결과:
[2 4 6]
파이썬 리스트에 대한 곱셈 연산의 결과:
[3, 6, 9]
--------------------------------------------------------------------------------
넘파이 배열에 대한 곱셈 연산의 결과:
[3 6 9]
--------------------------------------------------------------------------------
파이썬 리스트에 대한 평균 값: 2.0
--------------------------------------------------------------------------------
넘파이 배열에 대한 평균 값: 2.0

In [ ]:
# 대괄호가 중첩된 리스트 자료 구조 데이터 생성(조건: 성분 원소의 개수 동일)
list_data = [[1,2,3],[4,5,6],[7,8,9]]
print(f'대괄호가 중첩된 리스트 자료 구조 데이터 확인: \n{list_data}')

print('-'*80)

# 넘파이 배열로 변환 -> 엑셀과 같은 표(table: 행과 열) 구조 새성
array_data = np.array(list_data)
print(f'대괄호가 중첩된 리스트를 넘파이 배열로 변환한 결과: \n{array_data}')

대괄호가 중첩된 리스트 자료 구조 데이터 확인:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
--------------------------------------------------------------------------------
대괄호가 중첩된 리스트를 넘파이 배열로 변환한 결과:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

#인덱싱

In [ ]:
# 목표: 첫 번째 행, 첫 번째 열 -> 1 추출

## 1단계: 파이썬 방식 -> 변수[인덱스] -> 첫 번째 행 추출
result = array_data[0]
print(result)

print('-'*80)

## 2단계: 파이썬 방식 -> 변수[인덱스] -> 첫 번째 성분(첫 번째 열) 원소
result2 = result1[0]
print(result2)

print('-'*80)

## 넘파이 방식: 넘파이의 배열 모양(2행,3열) 이용 -> 변수 [행 인덱스, 열 인덱스]
result3 = array_data[0,0]
print(f'숫자 1을 인덱싱한 결과: {result3}')

[1 2 3]
--------------------------------------------------------------------------------
1
--------------------------------------------------------------------------------
숫자 1을 인덱싱한 결과: 1

# 넘파이 연습 문제

In [ ]:
# 문제1
array_data1 = np.array([10,20,30])
array_data2 = np.array([1,2,3])
result = array_data1 + array_data2
print(result)

[11 22 33]

In [ ]:
# 문제2
array_data = np.array([5,10,15])
result = array_data * 3
print(result)

[15 30 45]

In [ ]:
# 문제3
arr = np.array([10,30,50,70,90])
result = arr.mean()
print(result)

50.0

In [ ]:
# 문제4
array_data = np.array([]) # 빈 배열을 생성하려면 빈 리스트를 인수로 전달합니다.
# 또는 array_data = np.array([1, 2, 3]) # 다른 데이터로 배열을 생성할 수 있습니다.
print(array_data)

[]

In [ ]:
# 문제5

#판다스(pandas)

In [ ]:
# 필요한 라이브러리 임포트
import pandas as pd

## DataFrame 자료 구조 생성: csv 파일 처리

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# DataFrame 생성

## 파일 경로(위치) 설정
file_path = "/content/drive/MyDrive/KDT/ad_performance.csv"

## pd.read_csv() 호출
df = pd.read_csv(file_path)

## 결과 확인
# print(df)
display(df)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue
0,2025-01-01,Facebook,50s+,Male,15412,578,100308,27,723225
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303
3,2025-01-01,Organic,30s,Female,6866,686,81358,28,520546
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721
...,...,...,...,...,...,...,...,...,...
4995,2025-06-29,Organic,20s,Female,10064,933,180066,40,814096
4996,2025-06-29,Naver,40s,Male,5657,537,71261,7,256452
4997,2025-06-29,Organic,40s,Male,7331,378,159162,20,795243
4998,2025-06-29,Google,20s,Male,9272,124,173437,23,1293372
4999,2025-06-29,Naver,30s,Female,12688,733,193294,13,1000870

In [ ]:
print(range(0,1000))

range(0, 1000)

## 분해

In [ ]:
# 행 인덱스 추출
info_index = df.index
print(f'DataFrame의 행 인덱스: {info_index}')

print('-'*80)

# 컬럼 인덱스 추출
info_columns = df.columns
print(f'DataFrame의 컬럼 인덱스: {info_columns}')

print('-'*80)

# 값 추출
info_values = df.values
print(f'DataFrame의 값: \n{info_values}')

DataFrame의 행 인덱스: RangeIndex(start=0, stop=5000, step=1)
--------------------------------------------------------------------------------
DataFrame의 컬럼 인덱스: Index(['Date', 'Channel', 'Age_Group', 'Gender', 'Impressions', 'Clicks',
       'Cost', 'Conversions', 'Revenue'],
      dtype='object')
--------------------------------------------------------------------------------
DataFrame의 값:
[['2025-01-01' 'Facebook' '50s+' ... 100308 27 723225]
 ['2025-01-01' 'Google' '20s' ... 103029 26 1680444]
 ['2025-01-01' 'Naver' '50s+' ... 158046 48 1580303]
 ...
 ['2025-06-29' 'Organic' '40s' ... 159162 20 795243]
 ['2025-06-29' 'Google' '20s' ... 173437 23 1293372]
 ['2025-06-29' 'Naver' '30s' ... 193294 13 1000870]]

## 인덱싱

In [ ]:
# 특정 컬럼 인덱싱
channel = df["Channel"]
print(channel)

0       Facebook
1         Google
2          Naver
3        Organic
4          Naver
          ...
4995     Organic
4996       Naver
4997     Organic
4998      Google
4999       Naver
Name: Channel, Length: 5000, dtype: object

In [ ]:
# fancy 인덱싱: 변수[['컬럼1','컬럼4']]
df1 = df[['Channel','Clicks','Revenue']]
# print(df1)
display(df1)

       Channel  Clicks  Revenue
0     Facebook     578   723225
1       Google     897  1680444
2        Naver     471  1580303
3      Organic     686   520546
4        Naver     525  1505721
...        ...     ...      ...
4995   Organic     933   814096
4996     Naver     537   256452
4997   Organic     378   795243
4998    Google     124  1293372
4999     Naver     733  1000870

[5000 rows x 3 columns]

In [ ]:
print(df['Clicks']/df['Impressions'])

0       0.037503
1       0.074812
2       0.025455
3       0.099913
4       0.100000
          ...
4995    0.092707
4996    0.094927
4997    0.051562
4998    0.013374
4999    0.057771
Length: 5000, dtype: float64

##새로운 칼럼 추가(파생 변수 생성)

In [ ]:
# CTR (Click-Through Rate): 클릭률 컬럼 추가
print(df['Clicks'] / df['Impressions'])
display(df)

print('-'*100)

# CPC (Cost Per Click): 클릭당 비용 컬럼 추가
df['CPC'] = df['Cost'] / df['Clicks']
display(df)

# CVR (Conversion Rate): 전환율 컬럼 추가
df['CVR'] = df['Conversions'] / df['Clicks'] * 100

# CPA (Cost Per Acquisition): 전환당 비용 컬럼 추가
df['CPA'] = df['Cost'] / df['Conversions']

# ROAS (Return On Ad Spend): 광고비 대비 수익률 컬럼 추가
df['ROAS'] = df['Revenue'] / df['Cost'] * 100

# 최종 결과
display(df)

0       0.037503
1       0.074812
2       0.025455
3       0.099913
4       0.100000
          ...
4995    0.092707
4996    0.094927
4997    0.051562
4998    0.013374
4999    0.057771
Length: 5000, dtype: float64

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue
0,2025-01-01,Facebook,50s+,Male,15412,578,100308,27,723225
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303
3,2025-01-01,Organic,30s,Female,6866,686,81358,28,520546
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721
...,...,...,...,...,...,...,...,...,...
4995,2025-06-29,Organic,20s,Female,10064,933,180066,40,814096
4996,2025-06-29,Naver,40s,Male,5657,537,71261,7,256452
4997,2025-06-29,Organic,40s,Male,7331,378,159162,20,795243
4998,2025-06-29,Google,20s,Male,9272,124,173437,23,1293372
4999,2025-06-29,Naver,30s,Female,12688,733,193294,13,1000870

----------------------------------------------------------------------------------------------------

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue,CPC
0,2025-01-01,Facebook,50s+,Male,15412,578,100308,27,723225,173.543253
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444,114.859532
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303,335.554140
3,2025-01-01,Organic,30s,Female,6866,686,81358,28,520546,118.597668
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721,562.000000
...,...,...,...,...,...,...,...,...,...,...
4995,2025-06-29,Organic,20s,Female,10064,933,180066,40,814096,192.996785
4996,2025-06-29,Naver,40s,Male,5657,537,71261,7,256452,132.702048
4997,2025-06-29,Organic,40s,Male,7331,378,159162,20,795243,421.063492
4998,2025-06-29,Google,20s,Male,9272,124,173437,23,1293372,1398.685484
4999,2025-06-29,Naver,30s,Female,12688,733,193294,13,1000870,263.702592

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue,CPC,CVR,CPA,ROAS
0,2025-01-01,Facebook,50s+,Male,15412,578,100308,27,723225,173.543253,4.671280,3715.111111,721.004307
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444,114.859532,2.898551,3962.653846,1631.039804
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303,335.554140,10.191083,3292.625000,999.900662
3,2025-01-01,Organic,30s,Female,6866,686,81358,28,520546,118.597668,4.081633,2905.642857,639.821530
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721,562.000000,4.380952,12828.260870,510.327402
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,2025-06-29,Organic,20s,Female,10064,933,180066,40,814096,192.996785,4.287245,4501.650000,452.109782
4996,2025-06-29,Naver,40s,Male,5657,537,71261,7,256452,132.702048,1.303538,10180.142857,359.877072
4997,2025-06-29,Organic,40s,Male,7331,378,159162,20,795243,421.063492,5.291005,7958.100000,499.643759
4998,2025-06-29,Google,20s,Male,9272,124,173437,23,1293372,1398.685484,18.548387,7540.739130,745.730150
4999,2025-06-29,Naver,30s,Female,12688,733,193294,13,1000870,263.702592,1.773533,14868.769231,517.796724

In [ ]:
print(df['Clicks'])
print('-'*30)
print(df['Impressions'])

0       578
1       897
2       471
3       686
4       525
       ...
4995    933
4996    537
4997    378
4998    124
4999    733
Name: Clicks, Length: 5000, dtype: int64
------------------------------
0       15412
1       11990
2       18503
3        6866
4        5250
        ...
4995    10064
4996     5657
4997     7331
4998     9272
4999    12688
Name: Impressions, Length: 5000, dtype: int64

## 전용 함수

### query() 함수

#### 단일 조건(문자열)

In [ ]:
# Channel 컬럼의 값이 'Facebook'과 같은 경우
df1 = df.query("Channel == 'Facebook'")
display(df1)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue,CPC,CVR,CPA,ROAS
0,2025-01-01,Facebook,50s+,Male,15412,578,100308,27,723225,173.543253,4.671280,3715.111111,721.004307
5,2025-01-01,Facebook,30s,Male,11974,361,109972,39,1765516,304.631579,10.803324,2819.794872,1605.423199
6,2025-01-01,Facebook,30s,Female,14083,155,79464,1,424394,512.670968,0.645161,79464.000000,534.070774
8,2025-01-01,Facebook,20s,Female,15249,176,184655,1,271550,1049.176136,0.568182,184655.000000,147.058027
9,2025-01-01,Facebook,20s,Male,6518,651,57393,27,139854,88.161290,4.147465,2125.666667,243.677800
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4981,2025-06-29,Facebook,50s+,Male,11579,546,100479,34,1181886,184.027473,6.227106,2955.264706,1176.251754
4984,2025-06-29,Facebook,50s+,Male,8890,749,267827,37,757074,357.579439,4.939920,7238.567568,282.672770
4986,2025-06-29,Facebook,40s,Male,14067,727,102370,45,296552,140.811554,6.189821,2274.888889,289.686432
4988,2025-06-29,Facebook,50s+,Male,19235,973,217038,47,1704504,223.060637,4.830421,4617.829787,785.348188
4994,2025-06-29,Facebook,30s,Male,12482,429,250816,47,330298,584.652681,10.955711,5336.510638,131.689366

#### 단일 조건(숫자)

In [ ]:
# Revenue 컬럼의 값이 1500000 이상인 경우
df2 = df.query("Revenue >= 1500000")
display(df2)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue,CPC,CVR,CPA,ROAS
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444,114.859532,2.898551,3962.653846,1631.039804
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303,335.554140,10.191083,3292.625000,999.900662
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721,562.000000,4.380952,12828.260870,510.327402
5,2025-01-01,Facebook,30s,Male,11974,361,109972,39,1765516,304.631579,10.803324,2819.794872,1605.423199
7,2025-01-01,Google,40s,Male,14872,431,221715,17,1677619,514.419954,3.944316,13042.058824,756.655616
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4985,2025-06-29,Google,50s+,Male,8463,846,219915,9,1987591,259.946809,1.063830,24435.000000,903.799650
4987,2025-06-29,Naver,50s+,Female,13989,674,226994,17,1842078,336.786350,2.522255,13352.588235,811.509555
4988,2025-06-29,Facebook,50s+,Male,19235,973,217038,47,1704504,223.060637,4.830421,4617.829787,785.348188
4991,2025-06-29,Naver,20s,Female,8196,563,106645,36,1588784,189.422735,6.394316,2962.361111,1489.787613
4992,2025-06-29,Google,30s,Female,15117,282,218114,31,1912754,773.453901,10.992908,7035.935484,876.951502

#### 다중 조건(논리 연산자 and, or)

In [ ]:
# and 연산자: 모든 조건을 동시에 만족해야 되는 경우
df3 = df.query("Channel == 'Google' and Revenue >= 1500000")
print("Channel이 Google이면서 총 매출이 1500000이상인 행 추출")
display(df3)

Channel이 Google이면서 총 매출이 1500000이상인 행 추출

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue,CPC,CVR,CPA,ROAS
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444,114.859532,2.898551,3962.653846,1631.039804
7,2025-01-01,Google,40s,Male,14872,431,221715,17,1677619,514.419954,3.944316,13042.058824,756.655616
12,2025-01-01,Google,50s+,Female,14972,301,50832,19,1654250,168.877076,6.312292,2675.368421,3254.347655
13,2025-01-01,Google,40s,Female,16131,802,53791,35,1727164,67.071072,4.364090,1536.885714,3210.879143
18,2025-01-01,Google,40s,Female,11685,287,139501,15,1777642,486.066202,5.226481,9300.066667,1274.286206
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4938,2025-06-27,Google,50s+,Female,14760,487,276979,18,1795600,568.745380,3.696099,15387.722222,648.280195
4944,2025-06-27,Google,20s,Female,11164,823,113620,21,1924905,138.055893,2.551640,5410.476190,1694.160359
4979,2025-06-29,Google,20s,Female,17176,834,194693,47,1579548,233.444844,5.635492,4142.404255,811.301896
4985,2025-06-29,Google,50s+,Male,8463,846,219915,9,1987591,259.946809,1.063830,24435.000000,903.799650
4992,2025-06-29,Google,30s,Female,15117,282,218114,31,1912754,773.453901,10.992908,7035.935484,876.951502

In [ ]:
# or 연산자: 제시된 조건 중 하나만 만족해도 되는 경우
df4 = df.query("Age_Group == '20s' or Age_Group == '30s'")
print("연령대가 20대이거나 30대인 행 추출")
display(df4)

연령대가 20대이거나 30대인 행 추출

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue,CPC,CVR,CPA,ROAS
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444,114.859532,2.898551,3962.653846,1631.039804
3,2025-01-01,Organic,30s,Female,6866,686,81358,28,520546,118.597668,4.081633,2905.642857,639.821530
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721,562.000000,4.380952,12828.260870,510.327402
5,2025-01-01,Facebook,30s,Male,11974,361,109972,39,1765516,304.631579,10.803324,2819.794872,1605.423199
6,2025-01-01,Facebook,30s,Female,14083,155,79464,1,424394,512.670968,0.645161,79464.000000,534.070774
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4992,2025-06-29,Google,30s,Female,15117,282,218114,31,1912754,773.453901,10.992908,7035.935484,876.951502
4994,2025-06-29,Facebook,30s,Male,12482,429,250816,47,330298,584.652681,10.955711,5336.510638,131.689366
4995,2025-06-29,Organic,20s,Female,10064,933,180066,40,814096,192.996785,4.287245,4501.650000,452.109782
4998,2025-06-29,Google,20s,Male,9272,124,173437,23,1293372,1398.685484,18.548387,7540.739130,745.730150
4999,2025-06-29,Naver,30s,Female,12688,733,193294,13,1000870,263.702592,1.773533,14868.769231,517.796724

### value_counts() 함수

In [ ]:
# Channel 컬럼의 항목별 빈도수 측정
channel_counts = df['Channel'].value_counts()
print(f'Channel 칼럼의 항목별 빈도수: \n{channel_counts}')

Channel 칼럼의 항목별 빈도수:
Channel
Google       1506
Facebook     1479
Naver        1023
Instagram     537
Organic       455
Name: count, dtype: int64

# merge 함수

In [ ]:
# 데이터 불러오기

## 파일 경로 설정
file_path1 = '/content/drive/MyDrive/KDT/employee.csv'
file_path2 = '/content/drive/MyDrive/KDT/salary.csv'

## DataFrame 생성
df_employee = pd.read_csv(file_path1)
df_salary = pd.read_csv(file_path2)

## 결과 확인
display(df_employee)
print('-'*80)
display(df_salary)

   id name
0   1  홍길동
1   2  김철수
2   3  이영희
3   4  박민준

--------------------------------------------------------------------------------

   id  salary
0   3    3000
1   4    4000
2   5    5000
3   6    6000

In [ ]:
# how = 'left'
## 왼쪽 데이터프레임 기준으로 결합
df_merge_left = pd.merge(df_employee, df_salary, on='id', how='left')
display(df_merge_left)

   id name  salary
0   1  홍길동     NaN
1   2  김철수     NaN
2   3  이영희  3000.0
3   4  박민준  4000.0

In [ ]:
# how = 'right'
## 오른쪽 데이터프레임 기준으로 결합
df_merge_right = pd.merge(df_employee, df_salary, on='id', how='right')
display(df_merge_right)

   id name  salary
0   3  이영희    3000
1   4  박민준    4000
2   5  NaN    5000
3   6  NaN    6000

In [ ]:
# how = 'inner'

## 양쪽에 공통으로 존재하는 행만 결합
df_merge_inner = pd.merge(df_employee, df_salary, on='id', how='inner')
display(df_merge_inner)

   id name  salary
0   3  이영희    3000
1   4  박민준    4000

In [ ]:
# how = 'outer'

## 한쪽에만 존재하는 행도 결합
df_merge_outer = pd.merge(df_employee, df_salary, on='id', how='outer')
display(df_merge_outer)

   id name  salary
0   1  홍길동     NaN
1   2  김철수     NaN
2   3  이영희  3000.0
3   4  박민준  4000.0
4   5  NaN  5000.0
5   6  NaN  6000.0

# Pandas 연습 문제

In [132]:
# 문제1

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/KDT/ad_performance.csv')
display(df)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue
0,2025-01-01,Facebook,50s+,Male,15412,578,100308,27,723225
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303
3,2025-01-01,Organic,30s,Female,6866,686,81358,28,520546
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721
...,...,...,...,...,...,...,...,...,...
4995,2025-06-29,Organic,20s,Female,10064,933,180066,40,814096
4996,2025-06-29,Naver,40s,Male,5657,537,71261,7,256452
4997,2025-06-29,Organic,40s,Male,7331,378,159162,20,795243
4998,2025-06-29,Google,20s,Male,9272,124,173437,23,1293372
4999,2025-06-29,Naver,30s,Female,12688,733,193294,13,1000870

In [133]:
# 문제2
info_columns = df.columns
print(df.columns)

Index(['Date', 'Channel', 'Age_Group', 'Gender', 'Impressions', 'Clicks',
       'Cost', 'Conversions', 'Revenue'],
      dtype='object')

In [143]:
# 문제3
df_sub = df[['Channel', 'Age_Group', 'Revenue']]
print(df_sub)

       Channel Age_Group  Revenue
0     Facebook      50s+   723225
1       Google       20s  1680444
2        Naver      50s+  1580303
3      Organic       30s   520546
4        Naver       30s  1505721
...        ...       ...      ...
4995   Organic       20s   814096
4996     Naver       40s   256452
4997   Organic       40s   795243
4998    Google       20s  1293372
4999     Naver       30s  1000870

[5000 rows x 3 columns]

In [144]:
# 문제4
df['CPC'] = df['Cost']/df['Clicks']
display(df)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue,CPC
0,2025-01-01,Facebook,50s+,Male,15412,578,100308,27,723225,173.543253
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444,114.859532
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303,335.554140
3,2025-01-01,Organic,30s,Female,6866,686,81358,28,520546,118.597668
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721,562.000000
...,...,...,...,...,...,...,...,...,...,...
4995,2025-06-29,Organic,20s,Female,10064,933,180066,40,814096,192.996785
4996,2025-06-29,Naver,40s,Male,5657,537,71261,7,256452,132.702048
4997,2025-06-29,Organic,40s,Male,7331,378,159162,20,795243,421.063492
4998,2025-06-29,Google,20s,Male,9272,124,173437,23,1293372,1398.685484
4999,2025-06-29,Naver,30s,Female,12688,733,193294,13,1000870,263.702592

In [145]:
# 문제5
df_naver = df.query("Channel == 'Naver'")
display(df_naver)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue,CPC
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303,335.554140
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721,562.000000
25,2025-01-02,Naver,20s,Male,14492,956,173175,29,1790608,181.145397
26,2025-01-02,Naver,50s+,Female,8780,641,274416,31,1616186,428.106084
33,2025-01-02,Naver,20s,Female,17829,480,224353,47,1042465,467.402083
...,...,...,...,...,...,...,...,...,...,...
4989,2025-06-29,Naver,30s,Male,15739,832,241271,15,445842,289.989183
4990,2025-06-29,Naver,40s,Male,15270,903,62736,20,814202,69.475083
4991,2025-06-29,Naver,20s,Female,8196,563,106645,36,1588784,189.422735
4996,2025-06-29,Naver,40s,Male,5657,537,71261,7,256452,132.702048
4999,2025-06-29,Naver,30s,Female,12688,733,193294,13,1000870,263.702592

In [147]:
# 문제6
df_high_imp = df.query("Impressions >= 18000")
display(df_high_imp)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue,CPC
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303,335.554140
29,2025-01-02,Google,30s,Female,18607,540,88583,7,989354,164.042593
36,2025-01-02,Facebook,30s,Female,19168,937,65293,7,1678334,69.683031
41,2025-01-02,Google,20s,Male,18662,658,208900,12,719105,317.477204
48,2025-01-02,Google,40s,Male,18187,526,272648,22,1978862,518.342205
...,...,...,...,...,...,...,...,...,...,...
4943,2025-06-27,Naver,30s,Female,19461,692,147923,40,138734,213.761561
4947,2025-06-28,Instagram,40s,Male,18752,759,284808,47,334657,375.241107
4967,2025-06-28,Facebook,50s+,Female,19822,420,61638,45,1470401,146.757143
4968,2025-06-28,Naver,20s,Male,18815,610,245035,28,1927187,401.696721
4988,2025-06-29,Facebook,50s+,Male,19235,973,217038,47,1704504,223.060637

In [150]:
# 문제7
print(df['Age_Group'].value_counts())

Age_Group
50s+    1303
20s     1269
30s     1255
40s     1173
Name: count, dtype: int64

In [141]:
# 문제8
df1 = df.query("Channel")

In [142]:
# 문제9

In [ ]:
# 문제10